### PR TITLE
Add multiple parents callback support

### PR DESCRIPTION
**Pull request by solnic**
Refs #197

### CODE REVIEW

**Comment by robhanlon22** [comment]
@solnic There are a couple more references to `parents.last` as the single parent of a particular DSL. Do you think that those should also be made multiple parent-aware to prevent any future surprises?

**Comment by robhanlon22** [comment]
My mistake, there's only once reference left—within the `config` setting that I recently touched

**Comment by solnic** [comment]
@robhanlon22 tbh I'm not sure if we want to inherit config when there's more than one parent. I think people use multiple parents to compose a schema rather than to inherit configuration 🤔

**Comment by robhanlon22** [comment]
I'm actually with you on that—it might be surprising to have your config come from a parent when you're expecting the composition to be more or less stateless.

**Comment by solnic** [comment]
@robhanlon22 another option is to consider checking if all configs are equal and raise if they are not

**Comment by robhanlon22** [comment]
@solnic I feel like that would be the most correct but also the most disruptive. I think removing config inheritance and making it explicit would be best

**Pull request merged**
