### PR TITLE
Add error message to respond_to? predicate

### PR DESCRIPTION
**Pull request by rindek**
This was not reported on https://discourse.dry-rb.org/, though I think it can be treated as "typo", thus just straight PR:

When using Types.Interface, error is not produced in the `Dry::Schema::Result`

Ex.

```
Dry::Schema.Params { required(:a).filled(Types.Interface(:inv)) }.call(a: 1)
=> #<Dry::Schema::Result:0x1680>
```

The reason behind that is because errors message compiler can't find translation:
```
Dry::Schema::MissingMessageError (Message template for :a under "" was not found. Searched in:)
"en.dry_schema.errors.rules.a.respond_to?.arg.default"
"en.dry_schema.errors.rules.a.respond_to?"
"en.dry_schema.errors.respond_to?.failure"
"en.dry_schema.errors.respond_to?.value.a"
"en.dry_schema.errors.respond_to?.value.default.arg.default"
"en.dry_schema.errors.respond_to?.value.default"
"en.dry_schema.errors.respond_to?.arg.default"
"en.dry_schema.errors.respond_to?"
```

Expected:
```
Dry::Schema.Params { required(:a).filled(Types.Interface(:inv)) }.call(a: 1)
=> #<Dry::Schema::Result{:a=>1} errors={:a=>["must respond to inv"]}>
```

Adding a translation to `respond_to?` fixes the above issue

### CODE REVIEW

**Review by solnic — COMMENTED** [review]
Thanks, this makes sense. Any chance you could create a simple spec under spec/integration/schema/predicates/respond_to_spec.rb?

**Comment by rindek** [comment]
@solnic I've added tests but I managed to test only macro-way, as I found a bug

It looks like defining schema passing predicate directly to require/optional is broken

```
Dry::Schema.define { required(:foo) { respond_to?(:bar) } }
NoMethodError: undefined method `to_ast' for false:FalseClass
Did you mean?  to_s
from /Users/rindek/projects/dry-rb/dry-schema/lib/dry/schema/trace.rb:89:in `map'
```

My guess is that `respond_to?` in this case is calling `Object#respond_to?` instead of predicate definition from `dry-logic`

I've skipped failing tests, although I'm not sure what should be done with that bug

**Comment by solnic** [comment]
> My guess is that respond_to? in this case is calling Object#respond_to? instead of predicate definition from dry-logic

Correct. If you add `undef :respond_to?` here "lib/dry/schema/macros/dsl.rb" then it'll work.

**Comment by rindek** [comment]
@solnic I've added undef in the dsl, tests are green on MRI, but some fail on jruby (others than what I added)
Unfortunately I don't know jruby that much to figure out what exactly is the root cause, do you maybe have an idea?

**Comment by solnic** [comment]
> some fail on jruby (others than what I added)
Unfortunately I don't know jruby that much to figure out what exactly is the root cause, do you maybe have an idea?

thanks, this is confusing - I need to debug this under jruby :( The truth is, we should replace `respond_to?` predicate with some non-conflicting name. It was reported at least once that this predicate caused issues. Definitely something to do in 2.0.0.

**Comment by flash-gordon** [comment]
I'll cut a minor release in dry-logic, this should fix jruby failures https://github.com/dry-rb/dry-logic/pull/85

**Review by solnic — APPROVED** [review]

**Pull request merged**
