### PR TITLE
[WIP] OpenAPI properties generator

### PR DESCRIPTION
**Pull request by solnic**

### CODE REVIEW

**Comment by solnic** [comment]
Closing this experiment for now. I'll get back to it some time in the future.

**Comment by carlossilva** [comment]
@solnic this is exactly what I need, do you know if there has been any more work to be able to create OpenApi specs from dry-schema?

**Comment by solnic** [comment]
@carlossilva nope, this branch is as far as I got. It should be easy to finish it though but I have no interest in doing so at the moment, so somebody needs to help 😅

**Comment by elroadster** [comment]
Thanks for the reply @solnic is there more documentation on the events that are emitted when compiling the AST besides what is here? https://dry-rb.org/gems/dry-schema/1.5/advanced/rule-ast/

**Comment by solnic** [comment]
@elroadster I think [SchemaCompiler](https://github.com/dry-rb/dry-schema/blob/b1382acec41abac57173120331a2193063e00af6/lib/dry/schema/extensions/info/schema_compiler.rb) from the `info` extension should be a good reference.

**Pull request closed without merging**
