### PR TITLE
New processor steps interface and before/after step callbacks

### PR DESCRIPTION
**Pull request by skryukov**
This PR implements mentioned in #40 before/after step callbacks and refactors processor steps introducing new class `ProcessorSteps`.

I have some questions:
- should we just ignore callbacks on schema reusing (`required(:foo).schema(FooSchema)`)?
- when a base schema class is used (`Dry::Schema.define(parent: parent)`), should we override callbacks or stack them?
- is the current implementation of `ProcessorSteps` ok? =)

### CODE REVIEW

**Comment by solnic** [comment]
> should we just ignore callbacks on schema reusing (required(:foo).schema(FooSchema))?

We should probably execute them, but I reckon it's gonna be tricky to implement, right?

> when a base schema class is used (Dry::Schema.define(parent: parent)), should we override callbacks or stack them?

Stack them

> is the current implementation of ProcessorSteps ok? =)

Yes 😄

**Comment by skryukov** [comment]
@solnic thanks for your answers!

> We should probably execute them, but I reckon it's gonna be tricky to implement, right?

Yep, I can't even think of the way to implement it for now...

> Stack them

Changed behavior

**Comment by solnic** [comment]
>> We should probably execute them, but I reckon it's gonna be tricky to implement, right?
> Yep, I can't even think of the way to implement it for now...

yeah it's fine to leave it for now

**Comment by solnic** [comment]
@skryukov thanks for working on this. I'm gonna wrap it up and include in 1.4.0.

**Pull request merged**
